env:
  browser: true
extends: 'eslint:recommended'
parserOptions:
  ecmaVersion: 5
globals:
  $: false
  jQuery: false
  I18n: false
  locale: true
rules:
  indent:
    - warn
    - 2
    -
      SwitchCase: 1
      MemberExpression: 1
      FunctionDeclaration:
        body: 1
        parameters: 2
      CallExpression:
        arguments: 1
      ArrayExpression: 1
      ObjectExpression: 1

  linebreak-style:
    - warn
    - unix
  quotes:
    - warn
    - double
    -
      avoidEscape: true
  semi:
    - error
    - always
  camelcase:
    - warn
    -
      properties: never
      ignoreDestructuring: false
  brace-style:
    - warn
    - 1tbs
    -
      allowSingleLine: true
  comma-spacing:
    - warn
  multiline-comment-style:
    - warn
    - separate-lines
  spaced-comment:
    - warn
    - always
    -
      line:
        markers:
          - "="
      block:
        exceptions:
          - "*"
        balanced: true
  no-multiple-empty-lines:
    - error
    -
      max: 2
      maxBOF: 0
      maxEOF: 1
  unicode-bom:
    - error
    - never
  dot-location:
    - error
    - property
  dot-notation:
    - warn
  no-alert:
    warn
  no-console:
    warn
  no-eval:
    error
  valid-jsdoc:
    - error
    -
      prefer:
        arg: param
        argument: param
        return: returns
      preferType:
        object: Object
        array: Array
        list: Array
        hash: Object
        dict: Object
      requireReturn: false
      requireReturnType: true
      requireParamType: true
      requireParamDescription: true
      matchDescription: ".+"
      requireReturnDescription: true
  no-unused-vars:
    - error
    -
      vars: all
      argsIgnorePattern: "window|document|event|el|element|_"
